/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as quintySol from "./Quinty.sol";
export type { quintySol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { QuintyNFT } from "./QuintyNFT";
export type { QuintyReputation } from "./QuintyReputation";
