/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IQuintyReputationInterface extends Interface {
  getFunction(
    nameOrSignature: "recordBountyCreation" | "recordSubmission" | "recordWin"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "recordBountyCreation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSubmission",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordWin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "recordBountyCreation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordWin", data: BytesLike): Result;
}

export interface IQuintyReputation extends BaseContract {
  connect(runner?: ContractRunner | null): IQuintyReputation;
  waitForDeployment(): Promise<this>;

  interface: IQuintyReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  recordBountyCreation: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  recordSubmission: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  recordWin: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "recordBountyCreation"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordSubmission"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordWin"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  filters: {};
}
