/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Quinty {
  export type ReplyStruct = {
    replier: AddressLike;
    content: string;
    timestamp: BigNumberish;
  };

  export type ReplyStructOutput = [
    replier: string,
    content: string,
    timestamp: bigint
  ] & { replier: string; content: string; timestamp: bigint };

  export type SubmissionStruct = {
    solver: AddressLike;
    teamMembers: AddressLike[];
    blindedIpfsCid: string;
    revealIpfsCid: string;
    deposit: BigNumberish;
    replies: Quinty.ReplyStruct[];
    revealed: boolean;
    isTeam: boolean;
  };

  export type SubmissionStructOutput = [
    solver: string,
    teamMembers: string[],
    blindedIpfsCid: string,
    revealIpfsCid: string,
    deposit: bigint,
    replies: Quinty.ReplyStructOutput[],
    revealed: boolean,
    isTeam: boolean
  ] & {
    solver: string;
    teamMembers: string[];
    blindedIpfsCid: string;
    revealIpfsCid: string;
    deposit: bigint;
    replies: Quinty.ReplyStructOutput[];
    revealed: boolean;
    isTeam: boolean;
  };
}

export interface QuintyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReply"
      | "applyToOprec"
      | "approveOprecApplications"
      | "approvedParticipants"
      | "bounties"
      | "bountyCounter"
      | "createBounty"
      | "endOprecPhase"
      | "getBountyData"
      | "getOprecApplication"
      | "getOprecApplicationCount"
      | "getSubmission"
      | "getSubmissionCount"
      | "getSubmissionStruct"
      | "isApprovedParticipant"
      | "nftAddress"
      | "owner"
      | "rejectOprecApplications"
      | "renounceOwnership"
      | "reputationAddress"
      | "revealSolution"
      | "selectWinners"
      | "setAddresses"
      | "submitSolution"
      | "transferOwnership"
      | "triggerSlash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCreated"
      | "BountyResolved"
      | "BountySlashed"
      | "OprecApplicationApproved"
      | "OprecApplicationRejected"
      | "OprecApplicationSubmitted"
      | "OprecPhaseEnded"
      | "OwnershipTransferred"
      | "ReplyAdded"
      | "SolutionRevealed"
      | "SubmissionCreated"
      | "WinnersSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReply",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "applyToOprec",
    values: [BigNumberish, AddressLike[], string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approveOprecApplications",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedParticipants",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountyCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [
      string,
      BigNumberish,
      boolean,
      BigNumberish[],
      BigNumberish,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "endOprecPhase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBountyData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOprecApplication",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOprecApplicationCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissionCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissionStruct",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedParticipant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nftAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rejectOprecApplications",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealSolution",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "selectWinners",
    values: [BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddresses",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSolution",
    values: [BigNumberish, string, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerSlash",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addReply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "applyToOprec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveOprecApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountyCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endOprecPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBountyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOprecApplication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOprecApplicationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissionStruct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectOprecApplications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectWinners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerSlash",
    data: BytesLike
  ): Result;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish,
    hasOprec: boolean
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    amount: bigint,
    deadline: bigint,
    hasOprec: boolean
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    amount: bigint;
    deadline: bigint;
    hasOprec: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyResolvedEvent {
  export type InputTuple = [bountyId: BigNumberish];
  export type OutputTuple = [bountyId: bigint];
  export interface OutputObject {
    bountyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountySlashedEvent {
  export type InputTuple = [bountyId: BigNumberish, slashAmount: BigNumberish];
  export type OutputTuple = [bountyId: bigint, slashAmount: bigint];
  export interface OutputObject {
    bountyId: bigint;
    slashAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OprecApplicationApprovedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    applicationId: BigNumberish,
    applicant: AddressLike
  ];
  export type OutputTuple = [
    bountyId: bigint,
    applicationId: bigint,
    applicant: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    applicationId: bigint;
    applicant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OprecApplicationRejectedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    applicationId: BigNumberish,
    applicant: AddressLike
  ];
  export type OutputTuple = [
    bountyId: bigint,
    applicationId: bigint,
    applicant: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    applicationId: bigint;
    applicant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OprecApplicationSubmittedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    applicationId: BigNumberish,
    applicant: AddressLike,
    isTeam: boolean
  ];
  export type OutputTuple = [
    bountyId: bigint,
    applicationId: bigint,
    applicant: string,
    isTeam: boolean
  ];
  export interface OutputObject {
    bountyId: bigint;
    applicationId: bigint;
    applicant: string;
    isTeam: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OprecPhaseEndedEvent {
  export type InputTuple = [bountyId: BigNumberish];
  export type OutputTuple = [bountyId: bigint];
  export interface OutputObject {
    bountyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReplyAddedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    subId: BigNumberish,
    replier: AddressLike
  ];
  export type OutputTuple = [bountyId: bigint, subId: bigint, replier: string];
  export interface OutputObject {
    bountyId: bigint;
    subId: bigint;
    replier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolutionRevealedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    subId: BigNumberish,
    solver: AddressLike,
    revealIpfsCid: string
  ];
  export type OutputTuple = [
    bountyId: bigint,
    subId: bigint,
    solver: string,
    revealIpfsCid: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    subId: bigint;
    solver: string;
    revealIpfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    subId: BigNumberish,
    solver: AddressLike,
    ipfsCid: string,
    isTeam: boolean
  ];
  export type OutputTuple = [
    bountyId: bigint,
    subId: bigint,
    solver: string,
    ipfsCid: string,
    isTeam: boolean
  ];
  export interface OutputObject {
    bountyId: bigint;
    subId: bigint;
    solver: string;
    ipfsCid: string;
    isTeam: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnersSelectedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    winners: AddressLike[],
    submissionIds: BigNumberish[]
  ];
  export type OutputTuple = [
    bountyId: bigint,
    winners: string[],
    submissionIds: bigint[]
  ];
  export interface OutputObject {
    bountyId: bigint;
    winners: string[];
    submissionIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Quinty extends BaseContract {
  connect(runner?: ContractRunner | null): Quinty;
  waitForDeployment(): Promise<this>;

  interface: QuintyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReply: TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;

  applyToOprec: TypedContractMethod<
    [
      _bountyId: BigNumberish,
      _teamMembers: AddressLike[],
      _workExamples: string,
      _skillDescription: string
    ],
    [void],
    "nonpayable"
  >;

  approveOprecApplications: TypedContractMethod<
    [_bountyId: BigNumberish, _applicationIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  approvedParticipants: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        creator: string;
        description: string;
        amount: bigint;
        deadline: bigint;
        allowMultipleWinners: boolean;
        status: bigint;
        slashPercent: bigint;
        hasOprec: boolean;
        oprecDeadline: bigint;
      }
    ],
    "view"
  >;

  bountyCounter: TypedContractMethod<[], [bigint], "view">;

  createBounty: TypedContractMethod<
    [
      _description: string,
      _deadline: BigNumberish,
      _allowMultipleWinners: boolean,
      _winnerShares: BigNumberish[],
      _slashPercent: BigNumberish,
      _hasOprec: boolean,
      _oprecDeadline: BigNumberish
    ],
    [void],
    "payable"
  >;

  endOprecPhase: TypedContractMethod<
    [_bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBountyData: TypedContractMethod<
    [_bountyId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint[],
        bigint,
        bigint,
        string[],
        bigint[],
        boolean,
        bigint
      ] & {
        creator: string;
        description: string;
        amount: bigint;
        deadline: bigint;
        allowMultipleWinners: boolean;
        winnerShares: bigint[];
        status: bigint;
        slashPercent: bigint;
        selectedWinners: string[];
        selectedSubmissionIds: bigint[];
        hasOprec: boolean;
        oprecDeadline: bigint;
      }
    ],
    "view"
  >;

  getOprecApplication: TypedContractMethod<
    [_bountyId: BigNumberish, _appId: BigNumberish],
    [
      [string, string[], string, string, bigint, boolean, boolean] & {
        applicant: string;
        teamMembers: string[];
        workExamples: string;
        skillDescription: string;
        appliedAt: bigint;
        approved: boolean;
        rejected: boolean;
      }
    ],
    "view"
  >;

  getOprecApplicationCount: TypedContractMethod<
    [_bountyId: BigNumberish],
    [bigint],
    "view"
  >;

  getSubmission: TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish],
    [
      [bigint, string, string, bigint, string[], string, bigint] & {
        bountyId: bigint;
        solver: string;
        blindedIpfsCid: string;
        deposit: bigint;
        replies: string[];
        revealIpfsCid: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getSubmissionCount: TypedContractMethod<
    [_bountyId: BigNumberish],
    [bigint],
    "view"
  >;

  getSubmissionStruct: TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish],
    [Quinty.SubmissionStructOutput],
    "view"
  >;

  isApprovedParticipant: TypedContractMethod<
    [_bountyId: BigNumberish, _participant: AddressLike],
    [boolean],
    "view"
  >;

  nftAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rejectOprecApplications: TypedContractMethod<
    [_bountyId: BigNumberish, _applicationIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationAddress: TypedContractMethod<[], [string], "view">;

  revealSolution: TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish, _revealIpfsCid: string],
    [void],
    "nonpayable"
  >;

  selectWinners: TypedContractMethod<
    [
      _bountyId: BigNumberish,
      _winners: AddressLike[],
      _submissionIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  setAddresses: TypedContractMethod<
    [_repAddress: AddressLike, _nftAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  submitSolution: TypedContractMethod<
    [
      _bountyId: BigNumberish,
      _blindedIpfsCid: string,
      _teamMembers: AddressLike[]
    ],
    [void],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerSlash: TypedContractMethod<
    [_bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReply"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish, _content: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "applyToOprec"
  ): TypedContractMethod<
    [
      _bountyId: BigNumberish,
      _teamMembers: AddressLike[],
      _workExamples: string,
      _skillDescription: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveOprecApplications"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _applicationIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvedParticipants"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        creator: string;
        description: string;
        amount: bigint;
        deadline: bigint;
        allowMultipleWinners: boolean;
        status: bigint;
        slashPercent: bigint;
        hasOprec: boolean;
        oprecDeadline: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountyCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [
      _description: string,
      _deadline: BigNumberish,
      _allowMultipleWinners: boolean,
      _winnerShares: BigNumberish[],
      _slashPercent: BigNumberish,
      _hasOprec: boolean,
      _oprecDeadline: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "endOprecPhase"
  ): TypedContractMethod<[_bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBountyData"
  ): TypedContractMethod<
    [_bountyId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint[],
        bigint,
        bigint,
        string[],
        bigint[],
        boolean,
        bigint
      ] & {
        creator: string;
        description: string;
        amount: bigint;
        deadline: bigint;
        allowMultipleWinners: boolean;
        winnerShares: bigint[];
        status: bigint;
        slashPercent: bigint;
        selectedWinners: string[];
        selectedSubmissionIds: bigint[];
        hasOprec: boolean;
        oprecDeadline: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOprecApplication"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _appId: BigNumberish],
    [
      [string, string[], string, string, bigint, boolean, boolean] & {
        applicant: string;
        teamMembers: string[];
        workExamples: string;
        skillDescription: string;
        appliedAt: bigint;
        approved: boolean;
        rejected: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOprecApplicationCount"
  ): TypedContractMethod<[_bountyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish],
    [
      [bigint, string, string, bigint, string[], string, bigint] & {
        bountyId: bigint;
        solver: string;
        blindedIpfsCid: string;
        deposit: bigint;
        replies: string[];
        revealIpfsCid: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmissionCount"
  ): TypedContractMethod<[_bountyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubmissionStruct"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish],
    [Quinty.SubmissionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedParticipant"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _participant: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nftAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectOprecApplications"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _applicationIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revealSolution"
  ): TypedContractMethod<
    [_bountyId: BigNumberish, _subId: BigNumberish, _revealIpfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "selectWinners"
  ): TypedContractMethod<
    [
      _bountyId: BigNumberish,
      _winners: AddressLike[],
      _submissionIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAddresses"
  ): TypedContractMethod<
    [_repAddress: AddressLike, _nftAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitSolution"
  ): TypedContractMethod<
    [
      _bountyId: BigNumberish,
      _blindedIpfsCid: string,
      _teamMembers: AddressLike[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerSlash"
  ): TypedContractMethod<[_bountyId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "BountyResolved"
  ): TypedContractEvent<
    BountyResolvedEvent.InputTuple,
    BountyResolvedEvent.OutputTuple,
    BountyResolvedEvent.OutputObject
  >;
  getEvent(
    key: "BountySlashed"
  ): TypedContractEvent<
    BountySlashedEvent.InputTuple,
    BountySlashedEvent.OutputTuple,
    BountySlashedEvent.OutputObject
  >;
  getEvent(
    key: "OprecApplicationApproved"
  ): TypedContractEvent<
    OprecApplicationApprovedEvent.InputTuple,
    OprecApplicationApprovedEvent.OutputTuple,
    OprecApplicationApprovedEvent.OutputObject
  >;
  getEvent(
    key: "OprecApplicationRejected"
  ): TypedContractEvent<
    OprecApplicationRejectedEvent.InputTuple,
    OprecApplicationRejectedEvent.OutputTuple,
    OprecApplicationRejectedEvent.OutputObject
  >;
  getEvent(
    key: "OprecApplicationSubmitted"
  ): TypedContractEvent<
    OprecApplicationSubmittedEvent.InputTuple,
    OprecApplicationSubmittedEvent.OutputTuple,
    OprecApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OprecPhaseEnded"
  ): TypedContractEvent<
    OprecPhaseEndedEvent.InputTuple,
    OprecPhaseEndedEvent.OutputTuple,
    OprecPhaseEndedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReplyAdded"
  ): TypedContractEvent<
    ReplyAddedEvent.InputTuple,
    ReplyAddedEvent.OutputTuple,
    ReplyAddedEvent.OutputObject
  >;
  getEvent(
    key: "SolutionRevealed"
  ): TypedContractEvent<
    SolutionRevealedEvent.InputTuple,
    SolutionRevealedEvent.OutputTuple,
    SolutionRevealedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionCreated"
  ): TypedContractEvent<
    SubmissionCreatedEvent.InputTuple,
    SubmissionCreatedEvent.OutputTuple,
    SubmissionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "WinnersSelected"
  ): TypedContractEvent<
    WinnersSelectedEvent.InputTuple,
    WinnersSelectedEvent.OutputTuple,
    WinnersSelectedEvent.OutputObject
  >;

  filters: {
    "BountyCreated(uint256,address,uint256,uint256,bool)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "BountyResolved(uint256)": TypedContractEvent<
      BountyResolvedEvent.InputTuple,
      BountyResolvedEvent.OutputTuple,
      BountyResolvedEvent.OutputObject
    >;
    BountyResolved: TypedContractEvent<
      BountyResolvedEvent.InputTuple,
      BountyResolvedEvent.OutputTuple,
      BountyResolvedEvent.OutputObject
    >;

    "BountySlashed(uint256,uint256)": TypedContractEvent<
      BountySlashedEvent.InputTuple,
      BountySlashedEvent.OutputTuple,
      BountySlashedEvent.OutputObject
    >;
    BountySlashed: TypedContractEvent<
      BountySlashedEvent.InputTuple,
      BountySlashedEvent.OutputTuple,
      BountySlashedEvent.OutputObject
    >;

    "OprecApplicationApproved(uint256,uint256,address)": TypedContractEvent<
      OprecApplicationApprovedEvent.InputTuple,
      OprecApplicationApprovedEvent.OutputTuple,
      OprecApplicationApprovedEvent.OutputObject
    >;
    OprecApplicationApproved: TypedContractEvent<
      OprecApplicationApprovedEvent.InputTuple,
      OprecApplicationApprovedEvent.OutputTuple,
      OprecApplicationApprovedEvent.OutputObject
    >;

    "OprecApplicationRejected(uint256,uint256,address)": TypedContractEvent<
      OprecApplicationRejectedEvent.InputTuple,
      OprecApplicationRejectedEvent.OutputTuple,
      OprecApplicationRejectedEvent.OutputObject
    >;
    OprecApplicationRejected: TypedContractEvent<
      OprecApplicationRejectedEvent.InputTuple,
      OprecApplicationRejectedEvent.OutputTuple,
      OprecApplicationRejectedEvent.OutputObject
    >;

    "OprecApplicationSubmitted(uint256,uint256,address,bool)": TypedContractEvent<
      OprecApplicationSubmittedEvent.InputTuple,
      OprecApplicationSubmittedEvent.OutputTuple,
      OprecApplicationSubmittedEvent.OutputObject
    >;
    OprecApplicationSubmitted: TypedContractEvent<
      OprecApplicationSubmittedEvent.InputTuple,
      OprecApplicationSubmittedEvent.OutputTuple,
      OprecApplicationSubmittedEvent.OutputObject
    >;

    "OprecPhaseEnded(uint256)": TypedContractEvent<
      OprecPhaseEndedEvent.InputTuple,
      OprecPhaseEndedEvent.OutputTuple,
      OprecPhaseEndedEvent.OutputObject
    >;
    OprecPhaseEnded: TypedContractEvent<
      OprecPhaseEndedEvent.InputTuple,
      OprecPhaseEndedEvent.OutputTuple,
      OprecPhaseEndedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReplyAdded(uint256,uint256,address)": TypedContractEvent<
      ReplyAddedEvent.InputTuple,
      ReplyAddedEvent.OutputTuple,
      ReplyAddedEvent.OutputObject
    >;
    ReplyAdded: TypedContractEvent<
      ReplyAddedEvent.InputTuple,
      ReplyAddedEvent.OutputTuple,
      ReplyAddedEvent.OutputObject
    >;

    "SolutionRevealed(uint256,uint256,address,string)": TypedContractEvent<
      SolutionRevealedEvent.InputTuple,
      SolutionRevealedEvent.OutputTuple,
      SolutionRevealedEvent.OutputObject
    >;
    SolutionRevealed: TypedContractEvent<
      SolutionRevealedEvent.InputTuple,
      SolutionRevealedEvent.OutputTuple,
      SolutionRevealedEvent.OutputObject
    >;

    "SubmissionCreated(uint256,uint256,address,string,bool)": TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
    SubmissionCreated: TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;

    "WinnersSelected(uint256,address[],uint256[])": TypedContractEvent<
      WinnersSelectedEvent.InputTuple,
      WinnersSelectedEvent.OutputTuple,
      WinnersSelectedEvent.OutputObject
    >;
    WinnersSelected: TypedContractEvent<
      WinnersSelectedEvent.InputTuple,
      WinnersSelectedEvent.OutputTuple,
      WinnersSelectedEvent.OutputObject
    >;
  };
}
