/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IQuintyNFT,
  IQuintyNFTInterface,
} from "../../../contracts/interfaces/IQuintyNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "recipients",
        type: "address[]",
      },
      {
        internalType: "uint8",
        name: "badgeType",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
    ],
    name: "batchMintBadges",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "badgeType",
        type: "uint8",
      },
      {
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
    ],
    name: "mintBadge",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IQuintyNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IQuintyNFTInterface {
    return new Interface(_abi) as IQuintyNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IQuintyNFT {
    return new Contract(address, _abi, runner) as unknown as IQuintyNFT;
  }
}
