/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IQuintyReputation,
  IQuintyReputationInterface,
} from "../../../contracts/Quinty.sol/IQuintyReputation";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "recordBountyCreation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "recordSubmission",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "recordWin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IQuintyReputation__factory {
  static readonly abi = _abi;
  static createInterface(): IQuintyReputationInterface {
    return new Interface(_abi) as IQuintyReputationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IQuintyReputation {
    return new Contract(address, _abi, runner) as unknown as IQuintyReputation;
  }
}
